### ISSUE TITLE
[New req] ทางลูกค้าต้องการเพิ่มการชำระเงินด้วยธนบัตร

### ISSUE THREAD

**Issue by nitipatl** [BoatThanapon/problem-vending-machine#1]
ทางลูกค้าต้องการเพิ่มการชำระเงินด้วยธนบัตร 20, 50 และ 100 บาท
Hint : ซึ่งการออกแบบหรือพัฒนาซอฟแวร์ที่ดี ต้องสามารถทำให้การแก้ไขในครั้งต่อไปง่ายที่สุด
:)

**Comment by BoatThanapon** [comment]
เวลาทอนเงินลูกค้า ตู้จะทอนเงินเป็นธนบัตรกับเหรียญได้หรือทอนเป็นเหรียญได้แค่อย่างเดียว?

**Comment by nitipatl** [comment]
ทอนเป็นธนบัตรและเหรียญครับ

**Comment by BoatThanapon** [comment]
**Completed**
> ทางลูกค้าต้องการเพิ่มการชำระเงินด้วยธนบัตร 20, 50 และ 100 บาท
